<?php

namespace AppBundle\Repository;

/**
 * BeverageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeverageRepository extends \Doctrine\ORM\EntityRepository
{
}
