<?php

namespace AppBundle\Repository;

/**
 * DrankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrankRepository extends \Doctrine\ORM\EntityRepository
{
}
